corpus_options:
  # this is 13144 files
  paths:
    - /scratch/gpfs/PLI/hyen/data/dclm-dedup/data/dclm-dedup/*/*.parquet
  chunk_size: 256
  threshold_chunk_size: 32
  text_field: text
  metadata_fields: ["url"]
  num_workers: 8
  corpus_type: chunk
